import test from 'node:test';
import assert from 'node:assert/strict';
import { handleChunkRequest, ChunkIndex, usePostgresChunks } from '../src/http/chunks.mjs';
function response() { return { status: 0, body: null, writeHead(status) { this.status = status; }, end(text) { this.body = JSON.parse(text); } }; }
function world() { return { id: 'official', type: 'official', infinite: true, width: 1000, height: 1000, background: '#fff', access: { mode: 'public' }, lifecycle: { state: 'active' }, members: {}, pixels: { '1:2': { c: '#e50000' } } }; }
function withMode(mode, run) { const previous = process.env.CHUNK_READ_MODE; if (mode === undefined) delete process.env.CHUNK_READ_MODE; else process.env.CHUNK_READ_MODE = mode; return (async () => { try { return await run(); } finally { if (previous === undefined) delete process.env.CHUNK_READ_MODE; else process.env.CHUNK_READ_MODE = previous; } })(); }
test('Postgres chunk reader is used in postgres mode', async () => withMode('postgres', async () => { const w = world(), db = { worlds: { official: w } }, res = response(), mirror = { readChunks: async () => new Map([['0:0', [[1, 2, '#0083c7']]]]) }; await handleChunkRequest({ method: 'GET', url: '/api/worlds/official/chunks?cx=0&cy=0' }, res, { user: null, session: null }, db, new ChunkIndex(db), mirror); assert.equal(res.status, 200); assert.equal(res.body.storage, 'postgres'); assert.deepEqual(res.body.chunks[0].cells, [[1, 2, '#0083c7']]); }));
test('failed Postgres reader safely falls back to JSON index', async () => withMode('postgres', async () => { const w = world(), db = { worlds: { official: w } }, res = response(); await handleChunkRequest({ method: 'GET', url: '/api/worlds/official/chunks?cx=0&cy=0' }, res, { user: null, session: null }, db, new ChunkIndex(db), { readChunks: async () => { throw new Error('offline'); } }); assert.equal(res.body.storage, 'json'); assert.deepEqual(res.body.chunks[0].cells, [[1, 2, '#e50000']]); }));
test('default auto mode reads from Postgres when the mirror is connected', async () => withMode(undefined, async () => { assert.equal(usePostgresChunks({ readChunks: async () => new Map() }), true); assert.equal(usePostgresChunks(null), false); const w = world(), db = { worlds: { official: w } }, res = response(), mirror = { readChunks: async () => new Map([['0:0', [[3, 4, '#02be01']]]]) }; await handleChunkRequest({ method: 'GET', url: '/api/worlds/official/chunks?cx=0&cy=0' }, res, { user: null, session: null }, db, new ChunkIndex(db), mirror); assert.equal(res.body.storage, 'postgres'); assert.deepEqual(res.body.chunks[0].cells, [[3, 4, '#02be01']]); }));
test('json mode keeps the legacy in-memory path even with a mirror', async () => withMode('json', async () => { assert.equal(usePostgresChunks({ readChunks: async () => new Map() }), false); const w = world(), db = { worlds: { official: w } }, res = response(); let called = 0; await handleChunkRequest({ method: 'GET', url: '/api/worlds/official/chunks?cx=0&cy=0' }, res, { user: null, session: null }, db, new ChunkIndex(db), { readChunks: async () => { called += 1; return new Map(); } }); assert.equal(called, 0); assert.equal(res.body.storage, 'json'); assert.deepEqual(res.body.chunks[0].cells, [[1, 2, '#e50000']]); }));
