import { createServer } from 'node:http'; import { fileURLToPath } from 'node:url'; import { dirname, join } from 'node:path';
import { Store } from './src/core/db.mjs'; import { createPostgresMirror } from './src/core/postgres-mirror.mjs'; import { createUser, officialWorld } from './src/core/model.mjs'; import { normalizeWorldToolSettings } from './src/core/world-fixes.mjs'; import { hashPassword, now } from './src/core/util.mjs'; import { runAutomation } from './src/core/automation.mjs'; import { createSse } from './src/http/sse.mjs'; import { createApi } from './src/http/api.mjs'; import { ChunkIndex, handleChunkRequest } from './src/http/chunks.mjs'; import { handleWorldBootstrapRequest } from './src/http/world-bootstrap.mjs'; import { handlePlayerExperienceRequest } from './src/http/player-preferences.mjs'; import { checkCsrf, fail, getSession, isHttps, securityHeaders, serveStatic } from './src/http/kit.mjs';
const __dirname = dirname(fileURLToPath(import.meta.url)), PORT = Number(process.env.PORT || 3000), DATA_DIR = process.env.DATA_DIR || join(__dirname, 'data'), PUBLIC_DIR = join(__dirname, 'public'), APP_ORIGIN = process.env.APP_ORIGIN || '', AUTOMATION_INTERVAL_MS = Number(process.env.AUTOMATION_INTERVAL_MS || 60000);
async function bootstrap() { const store = new Store(DATA_DIR); await store.load(); const mirror = await createPostgresMirror(process.env.DATABASE_URL || ''); if (mirror) { store.addMirror(mirror); console.log('PostgreSQL dual-write mirror enabled'); } const db = store.db; if (!db.worlds.official) { db.worlds.official = officialWorld(); db.chats.official = []; } if (normalizeWorldToolSettings(db)) store.schedule(0);
	const adminNick = process.env.ADMIN_NICK, adminPassword = process.env.ADMIN_PASSWORD; if (adminNick && adminPassword && adminPassword.length >= 12) { let admin = Object.values(db.users).find((u) => u.nick.toLowerCase() === adminNick.toLowerCase()); if (!admin) { admin = createUser({ nick: adminNick, password: hashPassword(adminPassword), role: 'admin', verified: true }); db.users[admin.id] = admin; } else { admin.role = 'admin'; admin.password = hashPassword(adminPassword); } store.schedule(0); }
	const sse = createSse(), chunkIndex = new ChunkIndex(db), broadcast = sse.broadcast.bind(sse); sse.broadcast = (worldId, event, data) => { if (event === 'pixels') chunkIndex.applyPixels(worldId, data?.pixels); return broadcast(worldId, event, data); };
	const notify = (userId, message) => { const user = db.users[userId]; if (!user) return; (user.notifications ||= []).push({ id: `ntf_${now()}`, message, at: now(), read: false }); if (user.notifications.length > 50) user.notifications.splice(0, user.notifications.length - 50); };
	const api = createApi({ store, sse, notify }), tick = () => { try { const result = runAutomation(db, { emit: (worldId, event, data) => sse.broadcast(worldId, event, data), notify }); if (result?.changed) store.schedule(0); } catch (error) { console.error('automation tick failed:', error); } }; tick(); const timer = setInterval(tick, AUTOMATION_INTERVAL_MS); timer.unref?.();
	const server = createServer(async (req, res) => { const https = isHttps(req); securityHeaders(res, { https }); try { if (req.url.startsWith('/api/')) { const sessionInfo = getSession(db, req), ctx = { req, https, ip: (req.headers['x-forwarded-for']?.split(',')[0] || req.socket.remoteAddress || 'local').trim(), sid: sessionInfo?.sid || null, session: sessionInfo?.session || null, user: sessionInfo?.user || null }; if (await handleWorldBootstrapRequest(req, res, ctx, db, sse)) return; if (await handleChunkRequest(req, res, ctx, db, chunkIndex)) return; checkCsrf(req, ctx, APP_ORIGIN); if (await handlePlayerExperienceRequest(req, res, ctx, store)) return; const handled = await api.dispatch(req, res, ctx); if (normalizeWorldToolSettings(db)) store.schedule(); if (!handled) fail(res, Object.assign(new Error('Метод не найден'), { status: 404 })); return; } if (req.method !== 'GET' && req.method !== 'HEAD') return fail(res, Object.assign(new Error('Метод не поддерживается'), { status: 405 })); await serveStatic(req, res, PUBLIC_DIR); } catch (error) { fail(res, error); } });
	server.listen(PORT, () => console.log(`PixelFront Worlds v3 → http://localhost:${PORT}`)); const shutdown = async () => { clearInterval(timer); sse.close(); server.close(); await store.flush().catch(console.error); await mirror?.close().catch(console.error); process.exit(0); }; process.on('SIGINT', shutdown); process.on('SIGTERM', shutdown); }
bootstrap().catch((error) => { console.error(error); process.exit(1); });
