import http from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {existsSync,createReadStream} from 'node:fs';
import {join,extname,normalize} from 'node:path';
import {randomBytes,scryptSync,timingSafeEqual} from 'node:crypto';
import {URL} from 'node:url';

const PORT=Number(process.env.PORT||3000),DATA=process.env.DATA_DIR||'./data',FILE=join(DATA,'db.json'),PUBLIC=join(process.cwd(),'public');
const COLORS=['#f8f7f4','#202124','#e56458','#f1b84b','#46a171','#2783de','#7856c6','#e86aa3','#8b5a2b','#63c7d6'];
const fresh=()=>({users:{},worlds:{official:{id:'official',name:'Главный мир',description:'Официальный холст с рейтингом',type:'official',ownerId:null,width:128,height:80,cooldownMs:2500,maxEnergy:30,palette:COLORS,pixels:{},arts:{},public:true}},chats:{official:[]},reports:[],nextWorld:1});
let db=fresh();const sessions=new Map(),streams=new Map(),limits=new Map();let saveTimer;
const now=()=>Date.now(),id=p=>p+'_'+randomBytes(8).toString('hex'),clean=(v,n=120)=>String(v??'').replace(/[<>\u0000-\u001f]/g,'').trim().slice(0,n);
const send=(res,s,d,h={})=>{res.writeHead(s,{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...h});res.end(JSON.stringify(d))};
const fail=(res,s,e)=>send(res,s,{error:e});
async function input(req){let s='';for await(const c of req){s+=c;if(s.length>1e6)throw Error('Слишком большой запрос')}try{return s?JSON.parse(s):{}}catch{throw Error('Некорректный JSON')}}
const hash=(p,s=randomBytes(16).toString('hex'))=>s+':'+scryptSync(p,s,64).toString('hex');
function verify(p,x){const [s,h]=x.split(':'),a=Buffer.from(h,'hex'),b=scryptSync(p,s,64);return a.length===b.length&&timingSafeEqual(a,b)}
function cookie(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(v=>{let i=v.indexOf('=');return[v.slice(0,i).trim(),v.slice(i+1)]}))}
function user(req){const s=sessions.get(cookie(req).sid);return s&&s.until>now()?db.users[s.uid]:null}
const pub=u=>u&&({id:u.id,nick:u.nick,role:u.role,level:u.level,xp:u.xp,officialPixels:u.officialPixels,communityPixels:u.communityPixels,achievements:u.achievements});
function auth(req,res){const u=user(req);if(!u)fail(res,401,'Нужно войти');return u}
function limited(k,ms,max){let x=limits.get(k),t=now();if(!x||x.until<t)x={n:0,until:t+ms};x.n++;limits.set(k,x);return x.n>max}
function save(){clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{await mkdir(DATA,{recursive:true});await writeFile(FILE,JSON.stringify(db))},300)}
function energy(u,w){u.energy||={};let e=u.energy[w.id]||{value:w.maxEnergy,at:now()},g=Math.floor((now()-e.at)/w.cooldownMs);if(g){e.value=Math.min(w.maxEnergy,e.value+g);e.at+=g*w.cooldownMs}return u.energy[w.id]=e}
function emit(w,event,data){for(const r of streams.get(w)||[])r.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`)}
function view(w,u){return{...w,pixels:undefined,arts:Object.values(w.arts||{}),online:streams.get(w.id)?.size||0,canManage:!!u&&(u.role==='admin'||u.id===w.ownerId)}}
function match(path,pattern){const a=path.split('/').filter(Boolean),b=pattern.split('/').filter(Boolean),o={};if(a.length!==b.length)return;for(let i=0;i<a.length;i++){if(b[i][0]===':')o[b[i].slice(1)]=decodeURIComponent(a[i]);else if(a[i]!==b[i])return}return o}
async function api(req,res,url){const p=url.pathname,m=req.method,ip=req.socket.remoteAddress||'ip';if(limited('api'+ip,1e4,200))return fail(res,429,'Слишком много запросов');
 if(m==='POST'&&p==='/api/auth/register'){let b=await input(req),nick=clean(b.nick,24),pass=String(b.password||'');if(!/^[a-zA-Zа-яА-ЯёЁ0-9_-]{3,24}$/.test(nick))return fail(res,400,'Некорректный ник');if(pass.length<8)return fail(res,400,'Пароль минимум 8 символов');if(Object.values(db.users).some(x=>x.nick.toLowerCase()===nick.toLowerCase()))return fail(res,409,'Ник занят');let uid=id('usr'),u=db.users[uid]={id:uid,nick,password:hash(pass),role:'user',xp:0,level:1,officialPixels:0,communityPixels:0,achievements:[],energy:{}};let sid=id('ses');sessions.set(sid,{uid,until:now()+6048e5});save();return send(res,201,{user:pub(u)},{'set-cookie':`sid=${sid}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800`})}
 if(m==='POST'&&p==='/api/auth/login'){let b=await input(req),u=Object.values(db.users).find(x=>x.nick.toLowerCase()===String(b.nick||'').toLowerCase());if(!u||!verify(String(b.password||''),u.password))return fail(res,401,'Неверный ник или пароль');let sid=id('ses');sessions.set(sid,{uid:u.id,until:now()+6048e5});return send(res,200,{user:pub(u)},{'set-cookie':`sid=${sid}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800`})}
 if(m==='POST'&&p==='/api/auth/logout')return send(res,200,{ok:true},{'set-cookie':'sid=; Path=/; Max-Age=0'});
 if(m==='GET'&&p==='/api/me')return send(res,200,{user:pub(user(req))});
 if(m==='GET'&&p==='/api/worlds'){let u=user(req);return send(res,200,{worlds:Object.values(db.worlds).filter(w=>w.public||u&&(w.ownerId===u.id||u.role==='admin')).map(w=>view(w,u))})}
 if(m==='POST'&&p==='/api/worlds'){let u=auth(req,res);if(!u)return;let b=await input(req),wid='world-'+db.nextWorld++,w=db.worlds[wid]={id:wid,name:clean(b.name,40)||'Новый мир',description:clean(b.description,180),type:'community',ownerId:u.id,width:Math.max(32,Math.min(192,+b.width||96)),height:Math.max(24,Math.min(128,+b.height||64)),cooldownMs:Math.max(250,Math.min(60000,+b.cooldownMs||1000)),maxEnergy:Math.max(10,Math.min(500,+b.maxEnergy||100)),palette:COLORS,pixels:{},arts:{},public:true};db.chats[wid]=[];save();return send(res,201,{world:view(w,u)})}
 let q=match(p,'/api/worlds/:id');if(q&&m==='GET'){let w=db.worlds[q.id],u=user(req);if(!w)return fail(res,404,'Мир не найден');return send(res,200,{world:view(w,u),pixels:w.pixels,energy:u?energy(u,w):null})}
 q=match(p,'/api/worlds/:id/pixel');if(q&&m==='POST'){let u=auth(req,res),w=db.worlds[q.id];if(!u)return;if(!w)return fail(res,404,'Мир не найден');let b=await input(req),x=+b.x,y=+b.y;if(!Number.isInteger(x)||!Number.isInteger(y)||x<0||y<0||x>=w.width||y>=w.height||!w.palette.includes(b.color))return fail(res,400,'Некорректный пиксель');for(const a of Object.values(w.arts||{}))if(x>=a.x&&y>=a.y&&x<a.x+a.width&&y<a.y+a.height&&a.ownerId!==u.id&&w.ownerId!==u.id&&u.role!=='admin')return fail(res,403,'Арт защищён');let e=energy(u,w);if(e.value<1)return fail(res,429,'Энергия восстанавливается');e.value--;e.at=now();let px={x,y,color:b.color,userId:u.id,at:now()};w.pixels[`${x},${y}`]=px;if(w.type==='official'){u.officialPixels++;u.xp+=2;u.level=1+Math.floor(Math.sqrt(u.xp/100));if(u.officialPixels===1)u.achievements.push({key:'first',title:'Первый след'})}else u.communityPixels++;save();emit(w.id,'pixel',px);return send(res,201,{energy:e})}
 q=match(p,'/api/worlds/:id/chat');if(q&&m==='GET')return send(res,200,{messages:(db.chats[q.id]||[]).slice(-80)});if(q&&m==='POST'){let u=auth(req,res);if(!u)return;if(limited('chat'+u.id+q.id,1e4,8))return fail(res,429,'Не спамьте');let b=await input(req),text=clean(b.text,400);if(!text)return fail(res,400,'Пустое сообщение');let msg={id:id('msg'),userId:u.id,nick:u.nick,text,at:now()},a=db.chats[q.id]||=[];a.push(msg);if(a.length>500)a.shift();save();emit(q.id,'chat',msg);return send(res,201,{message:msg})}
 q=match(p,'/api/worlds/:id/arts');if(q&&m==='POST'){let u=auth(req,res),w=db.worlds[q.id];if(!u)return;if(!w||w.type==='official'||(w.ownerId!==u.id&&u.role!=='admin'))return fail(res,403,'Нет доступа');let b=await input(req),a={id:id('art'),name:clean(b.name,40)||'Арт',x:+b.x||0,y:+b.y||0,width:Math.max(1,+b.width||1),height:Math.max(1,+b.height||1),ownerId:u.id};if(a.x+a.width>w.width||a.y+a.height>w.height)return fail(res,400,'Область вне карты');w.arts[a.id]=a;save();emit(w.id,'art',a);return send(res,201,{art:a})}
 if(m==='GET'&&p==='/api/leaderboard')return send(res,200,{users:Object.values(db.users).sort((a,b)=>b.officialPixels-a.officialPixels).slice(0,50).map(pub),note:'Только официальный мир'});
 if(m==='POST'&&p==='/api/reports'){let u=auth(req,res);if(!u)return;let b=await input(req),r={id:id('rep'),reporterId:u.id,worldId:clean(b.worldId,40),reason:clean(b.reason,500),status:'open',at:now()};db.reports.push(r);save();return send(res,201,{report:r})}
 return fail(res,404,'Не найдено')}
function staticFile(res,url){let p=url.pathname==='/'?'/index.html':normalize(url.pathname),f=join(PUBLIC,p);if(!f.startsWith(PUBLIC)||!existsSync(f))return fail(res,404,'Не найдено');let t={'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css'}[extname(f)]||'application/octet-stream';res.writeHead(200,{'content-type':t});createReadStream(f).pipe(res)}
await mkdir(DATA,{recursive:true});if(existsSync(FILE))try{db=JSON.parse(await readFile(FILE,'utf8'))}catch{}
const an=process.env.ADMIN_NICK,ap=process.env.ADMIN_PASSWORD;if(an&&ap&&!Object.values(db.users).some(u=>u.role==='admin')){let uid=id('usr');db.users[uid]={id:uid,nick:an,password:hash(ap),role:'admin',xp:0,level:1,officialPixels:0,communityPixels:0,achievements:[],energy:{}};save()}
const server=http.createServer(async(req,res)=>{try{let u=new URL(req.url,'http://'+(req.headers.host||'localhost'));if(u.pathname==='/api/events'){let w=u.searchParams.get('world')||'official';res.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-cache','connection':'keep-alive'});res.write('event: ready\ndata: {}\n\n');if(!streams.has(w))streams.set(w,new Set());streams.get(w).add(res);return req.on('close',()=>streams.get(w)?.delete(res))}if(u.pathname.startsWith('/api/'))return api(req,res,u);staticFile(res,u)}catch(e){fail(res,400,e.message)}});server.listen(PORT,()=>console.log(`PixelFront Worlds: http://localhost:${PORT}`));
