import http from 'node:http';
import {readFile,writeFile,mkdir,rename,unlink} from 'node:fs/promises';
import {existsSync,createReadStream} from 'node:fs';
import {join,extname,resolve,sep} from 'node:path';
import {randomBytes,scryptSync,timingSafeEqual,createHash} from 'node:crypto';
import {URL} from 'node:url';

const PORT=Number(process.env.PORT||3000),DATA=resolve(process.env.DATA_DIR||'./data'),FILE=join(DATA,'db.json'),PUBLIC=resolve(process.cwd(),'public');
const SESSION_TTL=7*864e5,AUTO_ARCHIVE_DAYS=Math.max(0,Number(process.env.AUTO_ARCHIVE_DAYS||90)),HISTORY_LIMIT=Math.max(100,Number(process.env.PIXEL_HISTORY_LIMIT||10000)),AUDIT_LIMIT=Math.max(1000,Number(process.env.AUDIT_LIMIT||20000)),BODY_LIMIT=Math.max(65536,Number(process.env.BODY_LIMIT||1048576));
const COLORS=['#f8f7f4','#202124','#e56458','#f1b84b','#46a171','#2783de','#7856c6','#e86aa3','#8b5a2b','#63c7d6'];
const QUESTS=[{id:'pixels_5',title:'Поставить 5 пикселей',target:5,reward:{coins:25}},{id:'official_3',title:'Поставить 3 пикселя в официальном мире',target:3,reward:{item:'official_fragment',count:1}},{id:'chat_1',title:'Написать сообщение в чат',target:1,reward:{coins:5}}];
const now=()=>Date.now(),id=p=>p+'_'+randomBytes(10).toString('hex'),sha=v=>createHash('sha256').update(String(v)).digest('hex'),day=()=>new Date().toISOString().slice(0,10),clean=(v,n=120)=>String(v??'').replace(/[<>\u0000-\u001f]/g,'').trim().slice(0,n);
const fresh=()=>{let t=now();return{version:2,users:{},sessions:{},worlds:{official:{id:'official',name:'Главный мир',description:'Официальный холст с рейтингом',type:'official',ownerId:null,width:128,height:80,cooldownMs:2500,maxEnergy:30,palette:COLORS,pixels:{},pixelHistory:[],arts:{},public:true,createdAt:t,updatedAt:t,lastActivityAt:t,archivedAt:null}},chats:{official:[]},reports:[],audit:[],nextWorld:1}};
let db=fresh(),saveTimer,dirty=false,writeChain=Promise.resolve();const streams=new Map(),limits=new Map();
class HttpError extends Error{constructor(status,message){super(message);this.status=status}}
function daily(u){u.inventory||={coins:0,items:{}};u.inventory.items||={};if(!u.daily||u.daily.date!==day())u.daily={date:day(),quests:QUESTS.map(q=>({...q,progress:0,claimed:false}))};return u.daily}
function migrate(x){x=x&&typeof x==='object'?x:fresh();x.version=2;x.users||={};x.sessions||={};x.worlds||={};x.chats||={};x.reports=Array.isArray(x.reports)?x.reports:[];x.audit=Array.isArray(x.audit)?x.audit:[];x.nextWorld=Math.max(1,Number(x.nextWorld||1));if(!x.worlds.official)x.worlds.official=fresh().worlds.official;x.chats.official||=[];let t=now();for(const u of Object.values(x.users)){u.role=['user','moderator','admin'].includes(u.role)?u.role:'user';u.xp=Number(u.xp||0);u.level=Number(u.level||1);u.officialPixels=Number(u.officialPixels||0);u.communityPixels=Number(u.communityPixels||0);u.achievements=Array.isArray(u.achievements)?u.achievements:[];u.energy||={};u.inventory||={coins:0,items:{}};u.inventory.coins=Number(u.inventory.coins||0);u.inventory.items||={};daily(u)}for(const w of Object.values(x.worlds)){w.type=w.id==='official'?'official':'community';w.palette=Array.isArray(w.palette)&&w.palette.length?[...new Set(w.palette.filter(c=>COLORS.includes(c)))]:[...COLORS];w.pixels||={};w.pixelHistory=Array.isArray(w.pixelHistory)?w.pixelHistory:[];w.arts||={};w.public=w.public!==false;w.createdAt||=t;w.updatedAt||=w.createdAt;w.lastActivityAt||=w.updatedAt;w.archivedAt||=null;x.chats[w.id]||=[]}for(const r of x.reports){r.status||='open';r.createdAt||=r.at||t}return x}
function schedule(delay=100){dirty=true;clearTimeout(saveTimer);saveTimer=setTimeout(()=>flush().catch(e=>console.error('DB write failed:',e)),delay);saveTimer.unref?.()}
async function flush(){clearTimeout(saveTimer);saveTimer=null;if(!dirty)return writeChain;dirty=false;let data=JSON.stringify(db),tmp=FILE+'.tmp-'+process.pid+'-'+randomBytes(4).toString('hex');writeChain=writeChain.then(async()=>{await mkdir(DATA,{recursive:true});await writeFile(tmp,data,{mode:0o600});await rename(tmp,FILE)}).catch(async e=>{await unlink(tmp).catch(()=>{});throw e});await writeChain;if(dirty)return flush()}
function headers(req,res){res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; object-src 'none'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");if(https(req))res.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains')}
function send(res,s,d,h={}){if(res.writableEnded)return;res.writeHead(s,{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...h});res.end(JSON.stringify(d))}const fail=(res,s,e)=>send(res,s,{error:e});
function validate(v,d=0){if(d>20)throw new HttpError(400,'Слишком глубокий JSON');if(!v||typeof v!=='object')return;for(const k of Object.keys(v)){if(['__proto__','prototype','constructor'].includes(k))throw new HttpError(400,'Недопустимое поле');validate(v[k],d+1)}}
async function input(req){let a=[],n=0;for await(const c of req){n+=c.length;if(n>BODY_LIMIT)throw new HttpError(413,'Слишком большой запрос');a.push(c)}if(!n)return{};try{let v=JSON.parse(Buffer.concat(a).toString('utf8'));validate(v);return v}catch(e){if(e instanceof HttpError)throw e;throw new HttpError(400,'Некорректный JSON')}}
const hash=(p,s=randomBytes(16).toString('hex'))=>s+':'+scryptSync(p,s,64).toString('hex');
function verify(p,x){try{let[s,h]=String(x).split(':'),a=Buffer.from(h,'hex'),b=scryptSync(p,s,64);return a.length===b.length&&timingSafeEqual(a,b)}catch{return false}}
function equal(a,b){a=Buffer.from(String(a||''));b=Buffer.from(String(b||''));return a.length===b.length&&timingSafeEqual(a,b)}
function cookies(req){let o={};for(const p of String(req.headers.cookie||'').split(';')){let i=p.indexOf('=');if(i>0)o[p.slice(0,i).trim()]=p.slice(i+1).trim()}return o}
const https=req=>!!req.socket.encrypted||String(req.headers['x-forwarded-proto']||'').split(',')[0].trim()==='https';
const cookie=(req,token,age=604800)=>`sid=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${age}${https(req)?'; Secure':''}`;
function session(req){if(req._auth!==undefined)return req._auth;let token=cookies(req).sid;if(!token)return req._auth=null;let key=sha(token),s=db.sessions[key];if(!s||s.until<=now()||!db.users[s.uid]){if(s){delete db.sessions[key];schedule()}return req._auth=null}return req._auth={key,record:s,user:db.users[s.uid]}}
const user=req=>session(req)?.user||null;
function pub(u,own=false){if(!u)return null;let x={id:u.id,nick:u.nick,role:u.role,level:u.level,xp:u.xp,officialPixels:u.officialPixels,communityPixels:u.communityPixels,achievements:u.achievements};if(own){x.inventory=u.inventory;x.daily=daily(u)}return x}
function auth(req,res){let u=user(req);if(!u)fail(res,401,'Нужно войти');return u}function admin(req,res){let u=auth(req,res);if(!u)return null;if(u.role!=='admin'){fail(res,403,'Требуется роль администратора');return null}return u}
const moderates=u=>u&&(u.role==='moderator'||u.role==='admin'),manages=(u,w)=>!!u&&(moderates(u)||w.ownerId===u.id);
function limited(k,ms,max){let x=limits.get(k),t=now();if(!x||x.until<=t)x={n:0,until:t+ms};x.n++;limits.set(k,x);return x.n>max}
function origins(req){let a=String(process.env.APP_ORIGIN||'').split(',').map(x=>x.trim().replace(/\/$/,'')).filter(Boolean),host=String(req.headers.host||'');if(host)a.push((https(req)?'https':'http')+'://'+host);return new Set(a)}
function mutation(req,res,path){if(!['POST','PUT','PATCH','DELETE'].includes(req.method))return true;let allowed=origins(req),origin=req.headers.origin;if(origin){if(!allowed.has(String(origin).replace(/\/$/,''))){fail(res,403,'Недопустимый Origin');return false}return true}if(req.headers['sec-fetch-site']==='same-origin')return true;let ref=req.headers.referer;if(ref){try{if(allowed.has(new URL(ref).origin))return true}catch{}}if(path==='/api/auth/register'||path==='/api/auth/login')return true;let s=session(req),token=req.headers['x-csrf-token'];if(!s||!token||!equal(token,s.record.csrf)){fail(res,403,'Требуется CSRF token');return false}return true}
function newSession(uid){let token=randomBytes(32).toString('hex'),csrf=randomBytes(24).toString('hex');db.sessions[sha(token)]={uid,csrf,createdAt:now(),lastSeenAt:now(),until:now()+SESSION_TTL};schedule();return{token,csrf}}
function energy(u,w){u.energy||={};let t=now(),e=u.energy[w.id]||{value:w.maxEnergy,at:t},g=Math.floor((t-e.at)/Math.max(250,w.cooldownMs));if(g>0){e.value=Math.min(w.maxEnergy,e.value+g);e.at+=g*w.cooldownMs}return u.energy[w.id]=e}
function emit(w,event,data){for(const r of streams.get(w)||[])r.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`)}
function view(w,u){let{pixels,pixelHistory,...x}=w;return{...x,arts:Object.values(w.arts||{}),online:streams.get(w.id)?.size||0,canManage:manages(u,w)}}const visible=(w,u)=>(!w.archivedAt&&w.public)||manages(u,w);
function match(path,pattern){let a=path.split('/').filter(Boolean),b=pattern.split('/').filter(Boolean),o={};if(a.length!==b.length)return null;for(let i=0;i<a.length;i++){if(b[i][0]===':')o[b[i].slice(1)]=decodeURIComponent(a[i]);else if(a[i]!==b[i])return null}return o}
function audit(actor,action,type,entityId,metadata={}){db.audit.push({id:id('aud'),actorId:actor?.id||null,actorNick:actor?.nick||'system',action,entityType:type,entityId,metadata,at:now()});if(db.audit.length>AUDIT_LIMIT)db.audit.splice(0,db.audit.length-AUDIT_LIMIT)}
function touch(w){w.updatedAt=now();w.lastActivityAt=now()}function quest(u,key,n=1){let q=daily(u).quests.find(x=>x.id===key);if(q)q.progress=Math.min(q.target,Number(q.progress||0)+n)}
function history(w,e){w.pixelHistory.push({id:id('pxh'),...e,at:now()});if(w.pixelHistory.length>HISTORY_LIMIT)w.pixelHistory.splice(0,w.pixelHistory.length-HISTORY_LIMIT)}
function palette(v,fallback){if(!Array.isArray(v))return fallback;let p=[...new Set(v.filter(c=>COLORS.includes(c)))];return p.length?p:fallback}
function archive(w,actor,reason){if(w.type==='official'||w.archivedAt)return false;w.archivedAt=now();w.public=false;w.updatedAt=now();audit(actor,'world.archive','world',w.id,{reason});emit(w.id,'archived',{worldId:w.id,at:w.archivedAt});return true}
function cleanup(){let t=now(),changed=false;for(const[k,s]of Object.entries(db.sessions))if(s.until<=t||!db.users[s.uid]){delete db.sessions[k];changed=true}if(changed)schedule()}
function autoArchive(){if(!AUTO_ARCHIVE_DAYS)return;let cutoff=now()-AUTO_ARCHIVE_DAYS*864e5,changed=false;for(const w of Object.values(db.worlds))if(w.type==='community'&&!w.archivedAt&&Number(w.lastActivityAt||w.createdAt||0)<cutoff)changed=archive(w,null,'inactive')||changed;if(changed)schedule()}
async function resolveReport(req,res,rid){let u=admin(req,res);if(!u)return;let r=db.reports.find(x=>x.id===rid);if(!r)return fail(res,404,'Жалоба не найдена');if(r.status!=='open')return fail(res,409,'Жалоба уже обработана');let b=await input(req),resolution=clean(b.resolution,500);if(!resolution)return fail(res,400,'Укажите решение');r.status=b.status==='dismissed'?'dismissed':'resolved';r.resolution=resolution;r.resolvedBy=u.id;r.resolvedAt=now();if(b.archiveWorld===true){let w=db.worlds[r.worldId];if(w?.type==='community')archive(w,u,'report:'+r.id)}audit(u,'report.resolve','report',r.id,{status:r.status,worldId:r.worldId,archiveWorld:b.archiveWorld===true});schedule();return send(res,200,{report:r})}
async function api(req,res,url){let p=url.pathname,m=req.method,ip=req.socket.remoteAddress||'ip';if(limited('api:'+ip,1e4,200))return fail(res,429,'Слишком много запросов');if(!mutation(req,res,p))return;
 if(m==='POST'&&p==='/api/auth/register'){if(limited('register:'+ip,6e4,10))return fail(res,429,'Попробуйте позже');let b=await input(req),nick=clean(b.nick,24),pass=String(b.password||'');if(!/^[a-zA-Zа-яА-ЯёЁ0-9_-]{3,24}$/.test(nick))return fail(res,400,'Некорректный ник');if(pass.length<8||pass.length>200)return fail(res,400,'Пароль должен содержать от 8 до 200 символов');if(Object.values(db.users).some(x=>x.nick.toLowerCase()===nick.toLowerCase()))return fail(res,409,'Ник занят');let uid=id('usr'),u=db.users[uid]={id:uid,nick,password:hash(pass),role:'user',xp:0,level:1,officialPixels:0,communityPixels:0,achievements:[],energy:{},inventory:{coins:0,items:{}},createdAt:now()};daily(u);let s=newSession(uid);audit(u,'user.register','user',uid);return send(res,201,{user:pub(u,true),csrfToken:s.csrf},{'set-cookie':cookie(req,s.token)})}
 if(m==='POST'&&p==='/api/auth/login'){if(limited('login:'+ip,6e4,15))return fail(res,429,'Попробуйте позже');let b=await input(req),u=Object.values(db.users).find(x=>x.nick.toLowerCase()===String(b.nick||'').toLowerCase());if(!u||!verify(String(b.password||''),u.password))return fail(res,401,'Неверный ник или пароль');let s=newSession(u.id);audit(u,'user.login','user',u.id);schedule();return send(res,200,{user:pub(u,true),csrfToken:s.csrf},{'set-cookie':cookie(req,s.token)})}
 if(m==='POST'&&p==='/api/auth/logout'){let s=session(req);if(s){delete db.sessions[s.key];audit(s.user,'user.logout','user',s.user.id);schedule()}return send(res,200,{ok:true},{'set-cookie':cookie(req,'',0)})}
 if(m==='GET'&&p==='/api/me'){let s=session(req);return send(res,200,{user:pub(s?.user,true),csrfToken:s?.record.csrf||null})}
 if(m==='GET'&&p==='/api/worlds'){let u=user(req);return send(res,200,{worlds:Object.values(db.worlds).filter(w=>visible(w,u)).map(w=>view(w,u))})}
 if(m==='POST'&&p==='/api/worlds'){let u=auth(req,res);if(!u)return;let b=await input(req),wid='world-'+db.nextWorld++,t=now(),w=db.worlds[wid]={id:wid,name:clean(b.name,40)||'Новый мир',description:clean(b.description,180),type:'community',ownerId:u.id,width:Math.max(32,Math.min(192,Number(b.width)||96)),height:Math.max(24,Math.min(128,Number(b.height)||64)),cooldownMs:Math.max(250,Math.min(60000,Number(b.cooldownMs)||1000)),maxEnergy:Math.max(10,Math.min(500,Number(b.maxEnergy)||100)),palette:palette(b.palette,[...COLORS]),pixels:{},pixelHistory:[],arts:{},public:b.public!==false,createdAt:t,updatedAt:t,lastActivityAt:t,archivedAt:null};db.chats[wid]=[];audit(u,'world.create','world',wid);schedule();return send(res,201,{world:view(w,u)})}
 let q=match(p,'/api/worlds/:id');if(q&&m==='GET'){let w=db.worlds[q.id],u=user(req);if(!w||!visible(w,u))return fail(res,404,'Мир не найден');return send(res,200,{world:view(w,u),pixels:w.pixels,energy:u&&!w.archivedAt?energy(u,w):null})}
 if(q&&m==='PATCH'){let u=auth(req,res),w=db.worlds[q.id];if(!u)return;if(!w)return fail(res,404,'Мир не найден');if(w.type!=='community'||!manages(u,w))return fail(res,403,'Нет доступа');if(w.archivedAt)return fail(res,409,'Мир архивирован');let b=await input(req),before={name:w.name,description:w.description,cooldownMs:w.cooldownMs,maxEnergy:w.maxEnergy,palette:w.palette,public:w.public};if('name'in b)w.name=clean(b.name,40)||w.name;if('description'in b)w.description=clean(b.description,180);if('cooldownMs'in b)w.cooldownMs=Math.max(250,Math.min(60000,Number(b.cooldownMs)||w.cooldownMs));if('maxEnergy'in b)w.maxEnergy=Math.max(10,Math.min(500,Number(b.maxEnergy)||w.maxEnergy));if('palette'in b)w.palette=palette(b.palette,w.palette);if('public'in b)w.public=Boolean(b.public);touch(w);audit(u,'world.settings.update','world',w.id,{before,after:{name:w.name,description:w.description,cooldownMs:w.cooldownMs,maxEnergy:w.maxEnergy,palette:w.palette,public:w.public}});schedule();emit(w.id,'settings',view(w,u));return send(res,200,{world:view(w,u)})}
 q=match(p,'/api/worlds/:id/archive');if(q&&m==='POST'){let u=auth(req,res),w=db.worlds[q.id];if(!u)return;if(!w)return fail(res,404,'Мир не найден');if(w.type==='official')return fail(res,400,'Официальный мир нельзя архивировать');if(!manages(u,w))return fail(res,403,'Нет доступа');archive(w,u,clean((await input(req)).reason,200)||'manual');schedule();return send(res,200,{world:view(w,u)})}
 q=match(p,'/api/worlds/:id/pixel');if(q&&m==='POST'){let u=auth(req,res),w=db.worlds[q.id];if(!u)return;if(!w||w.archivedAt||!visible(w,u))return fail(res,404,'Мир не найден');let b=await input(req),x=Number(b.x),y=Number(b.y);if(!Number.isInteger(x)||!Number.isInteger(y)||x<0||y<0||x>=w.width||y>=w.height||!w.palette.includes(b.color))return fail(res,400,'Некорректный пиксель');for(const a of Object.values(w.arts||{}))if(x>=a.x&&y>=a.y&&x<a.x+a.width&&y<a.y+a.height&&a.ownerId!==u.id&&w.ownerId!==u.id&&!moderates(u))return fail(res,403,'Арт защищён');let e=energy(u,w);if(e.value<1)return fail(res,429,'Энергия восстанавливается');e.value--;e.at=now();let key=x+','+y,before=w.pixels[key]?{...w.pixels[key]}:null,px={x,y,color:b.color,userId:u.id,at:now()};w.pixels[key]=px;history(w,{type:'place',x,y,before,after:px,actorId:u.id});if(w.type==='official'){u.officialPixels++;u.xp+=2;u.level=1+Math.floor(Math.sqrt(u.xp/100));quest(u,'official_3');if(u.officialPixels===1&&!u.achievements.some(a=>a.key==='first'))u.achievements.push({key:'first',title:'Первый след'})}else u.communityPixels++;quest(u,'pixels_5');touch(w);schedule();emit(w.id,'pixel',px);return send(res,201,{energy:e})}
 q=match(p,'/api/worlds/:id/pixel-history')||match(p,'/api/worlds/:id/pixels/history');if(q&&m==='GET'){let u=auth(req,res),w=db.worlds[q.id];if(!u)return;if(!w)return fail(res,404,'Мир не найден');if(!manages(u,w))return fail(res,403,'Нет доступа');let x=url.searchParams.has('x')?Number(url.searchParams.get('x')):null,y=url.searchParams.has('y')?Number(url.searchParams.get('y')):null,limit=Math.max(1,Math.min(500,Number(url.searchParams.get('limit')||100))),h=w.pixelHistory;if(Number.isInteger(x))h=h.filter(e=>e.x===x);if(Number.isInteger(y))h=h.filter(e=>e.y===y);return send(res,200,{history:h.slice(-limit).reverse()})}
 q=match(p,'/api/worlds/:id/rollback')||match(p,'/api/worlds/:id/pixels/rollback');if(q&&m==='POST'){let u=auth(req,res),w=db.worlds[q.id];if(!u)return;if(!w)return fail(res,404,'Мир не найден');if(!manages(u,w))return fail(res,403,'Нет доступа');if(w.archivedAt)return fail(res,409,'Мир архивирован');let b=await input(req),target=b.historyId?w.pixelHistory.find(e=>e.id===b.historyId):[...w.pixelHistory].reverse().find(e=>e.x===Number(b.x)&&e.y===Number(b.y));if(!target)return fail(res,404,'Запись истории не найдена');let key=target.x+','+target.y,before=w.pixels[key]?{...w.pixels[key]}:null,restored=target.before?{...target.before,at:now()}:null;if(restored)w.pixels[key]=restored;else delete w.pixels[key];history(w,{type:'rollback',x:target.x,y:target.y,before,after:restored,actorId:u.id,targetHistoryId:target.id});touch(w);audit(u,'pixel.rollback','world',w.id,{x:target.x,y:target.y,targetHistoryId:target.id});schedule();emit(w.id,'pixel',restored||{x:target.x,y:target.y,color:w.palette[0],removed:true,at:now()});return send(res,200,{pixel:restored,x:target.x,y:target.y})}
 q=match(p,'/api/worlds/:id/chat');if(q&&m==='GET'){let w=db.worlds[q.id],u=user(req);if(!w||!visible(w,u))return fail(res,404,'Мир не найден');return send(res,200,{messages:(db.chats[q.id]||[]).slice(-80)})}if(q&&m==='POST'){let u=auth(req,res),w=db.worlds[q.id];if(!u)return;if(!w||w.archivedAt||!visible(w,u))return fail(res,404,'Мир не найден');if(limited('chat:'+u.id+':'+q.id,1e4,8))return fail(res,429,'Не спамьте');let b=await input(req),text=clean(b.text,400);if(!text)return fail(res,400,'Пустое сообщение');let msg={id:id('msg'),userId:u.id,nick:u.nick,text,at:now()},a=db.chats[q.id]||=[];a.push(msg);if(a.length>500)a.splice(0,a.length-500);quest(u,'chat_1');touch(w);schedule();emit(q.id,'chat',msg);return send(res,201,{message:msg})}
 q=match(p,'/api/worlds/:id/arts');if(q&&m==='POST'){let u=auth(req,res),w=db.worlds[q.id];if(!u)return;if(!w||w.archivedAt||w.type==='official'||!manages(u,w))return fail(res,403,'Нет доступа');let b=await input(req),a={id:id('art'),name:clean(b.name,40)||'Арт',x:Number(b.x)||0,y:Number(b.y)||0,width:Math.max(1,Number(b.width)||1),height:Math.max(1,Number(b.height)||1),ownerId:u.id};if(!Number.isInteger(a.x)||!Number.isInteger(a.y)||!Number.isInteger(a.width)||!Number.isInteger(a.height)||a.x<0||a.y<0||a.x+a.width>w.width||a.y+a.height>w.height)return fail(res,400,'Область вне карты');w.arts[a.id]=a;touch(w);audit(u,'art.create','world',w.id,{artId:a.id});schedule();emit(w.id,'art',a);return send(res,201,{art:a})}
 if(m==='GET'&&p==='/api/leaderboard')return send(res,200,{users:Object.values(db.users).sort((a,b)=>b.officialPixels-a.officialPixels).slice(0,50).map(x=>pub(x)),note:'Только официальный мир'});
 if(m==='POST'&&p==='/api/reports'){let u=auth(req,res);if(!u)return;if(limited('report:'+u.id,36e5,10))return fail(res,429,'Слишком много жалоб');let b=await input(req),worldId=clean(b.worldId,40),reason=clean(b.reason,500);if(!db.worlds[worldId])return fail(res,404,'Мир не найден');if(!reason)return fail(res,400,'Укажите причину');let r={id:id('rep'),reporterId:u.id,worldId,reason,status:'open',createdAt:now(),at:now()};db.reports.push(r);audit(u,'report.create','report',r.id,{worldId});schedule();return send(res,201,{report:r})}
 if(m==='GET'&&p==='/api/admin/reports'){let u=admin(req,res);if(!u)return;let status=clean(url.searchParams.get('status')||'open',20),limit=Math.max(1,Math.min(200,Number(url.searchParams.get('limit')||50))),offset=Math.max(0,Number(url.searchParams.get('offset')||0)),rs=db.reports.filter(r=>status==='all'||r.status===status).sort((a,b)=>b.createdAt-a.createdAt);return send(res,200,{reports:rs.slice(offset,offset+limit),total:rs.length,nextOffset:offset+limit<rs.length?offset+limit:null})}
 q=m==='POST'?match(p,'/api/admin/reports/:id/resolve'):m==='PATCH'?match(p,'/api/admin/reports/:id'):null;if(q)return resolveReport(req,res,q.id);
 if(m==='GET'&&p==='/api/admin/audit'){let u=admin(req,res);if(!u)return;let limit=Math.max(1,Math.min(500,Number(url.searchParams.get('limit')||100))),before=Number(url.searchParams.get('before')||Infinity),entityId=clean(url.searchParams.get('entityId')||'',100),action=clean(url.searchParams.get('action')||'',100),a=db.audit.filter(e=>e.at<before);if(entityId)a=a.filter(e=>e.entityId===entityId);if(action)a=a.filter(e=>e.action===action);a=a.sort((x,y)=>y.at-x.at).slice(0,limit);return send(res,200,{audit:a,nextBefore:a.length===limit?a.at(-1).at:null})}
 if(m==='GET'&&(p==='/api/quests/daily'||p==='/api/quests')){let u=auth(req,res);if(!u)return;return send(res,200,{daily:daily(u),inventory:u.inventory})}
 q=match(p,'/api/quests/daily/:id/claim');if(q&&m==='POST'){let u=auth(req,res);if(!u)return;let item=daily(u).quests.find(x=>x.id===q.id);if(!item)return fail(res,404,'Задание не найдено');if(item.claimed)return fail(res,409,'Награда уже получена');if(item.progress<item.target)return fail(res,409,'Задание не завершено');item.claimed=true;if(item.reward.coins)u.inventory.coins+=item.reward.coins;if(item.reward.item)u.inventory.items[item.reward.item]=Number(u.inventory.items[item.reward.item]||0)+Number(item.reward.count||1);audit(u,'quest.claim','user',u.id,{questId:item.id});schedule();return send(res,200,{quest:item,inventory:u.inventory})}
 if(m==='GET'&&p==='/api/inventory'){let u=auth(req,res);if(!u)return;return send(res,200,{inventory:u.inventory})}
 return fail(res,404,'Не найдено')}
function staticFile(req,res,url){if(!['GET','HEAD'].includes(req.method))return fail(res,405,'Метод не поддерживается');let p;try{p=decodeURIComponent(url.pathname)}catch{return fail(res,400,'Некорректный путь')}if(p==='/')p='/index.html';let f=resolve(PUBLIC,'.'+p);if(f!==PUBLIC&&!f.startsWith(PUBLIC+sep))return fail(res,403,'Нет доступа');if(!existsSync(f))return fail(res,404,'Не найдено');let t={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.ico':'image/x-icon'}[extname(f).toLowerCase()]||'application/octet-stream';res.writeHead(200,{'content-type':t,'cache-control':extname(f)==='.html'?'no-cache':'public, max-age=3600'});if(req.method==='HEAD')return res.end();createReadStream(f).on('error',()=>res.destroy()).pipe(res)}
await mkdir(DATA,{recursive:true});if(existsSync(FILE))try{db=migrate(JSON.parse(await readFile(FILE,'utf8')))}catch(e){console.error('Cannot read database, using fresh data:',e);db=fresh()}else db=fresh();
const an=process.env.ADMIN_NICK,ap=process.env.ADMIN_PASSWORD;if(an&&ap&&!Object.values(db.users).some(u=>u.role==='admin')){let uid=id('usr'),u=db.users[uid]={id:uid,nick:clean(an,24),password:hash(ap),role:'admin',xp:0,level:1,officialPixels:0,communityPixels:0,achievements:[],energy:{},inventory:{coins:0,items:{}},createdAt:now()};daily(u);audit(u,'admin.bootstrap','user',uid);schedule(0)}cleanup();autoArchive();schedule(0);await flush();
const maintenance=setInterval(()=>{cleanup();autoArchive()},216e5);maintenance.unref();
const server=http.createServer(async(req,res)=>{headers(req,res);try{let url=new URL(req.url,'http://'+(req.headers.host||'localhost'));if(url.pathname==='/api/events'){if(req.method!=='GET')return fail(res,405,'Метод не поддерживается');let wid=clean(url.searchParams.get('world')||'official',40),w=db.worlds[wid],u=user(req);if(!w||!visible(w,u))return fail(res,404,'Мир не найден');res.writeHead(200,{'content-type':'text/event-stream; charset=utf-8','cache-control':'no-cache, no-transform','connection':'keep-alive','x-accel-buffering':'no'});res.write('event: ready\ndata: {}\n\n');if(!streams.has(wid))streams.set(wid,new Set());streams.get(wid).add(res);let ping=setInterval(()=>res.write(': ping\n\n'),25000);ping.unref();return req.on('close',()=>{clearInterval(ping);streams.get(wid)?.delete(res);if(!streams.get(wid)?.size)streams.delete(wid)})}if(url.pathname.startsWith('/api/'))return await api(req,res,url);return staticFile(req,res,url)}catch(e){console.error(e);if(!res.headersSent)fail(res,e.status||500,e.status?e.message:'Внутренняя ошибка');else res.destroy()}});
async function shutdown(signal){console.log(signal+': saving database');server.close();clearInterval(maintenance);try{await flush()}finally{process.exit(0)}}process.once('SIGINT',()=>shutdown('SIGINT'));process.once('SIGTERM',()=>shutdown('SIGTERM'));server.listen(PORT,()=>console.log(`PixelFront Worlds v2: http://localhost:${PORT}`));
