// Атомарная JSON-персистентность с опциональными dual-write mirrors.
import { mkdir, open, readFile, rename, unlink } from 'node:fs/promises'; import { existsSync } from 'node:fs'; import { join, resolve } from 'node:path'; import { randomBytes } from 'node:crypto'; import { freshDb, migrate } from './model.mjs'; import { id, now } from './util.mjs';
const IGNORABLE_SYNC = new Set(['EPERM', 'EINVAL', 'ENOTSUP', 'EISDIR', 'EACCES', 'ENOSYS']);
async function syncQuietly(handle) { try { await handle.sync(); } catch (error) { if (!IGNORABLE_SYNC.has(error.code)) throw error; } }
export class Store {
	constructor(dir = './data') { this.dir = resolve(dir); this.file = join(this.dir, 'db.json'); this.db = freshDb(); this.dirty = false; this.timer = null; this.chain = Promise.resolve(); this.auditLimit = Math.max(1000, Number(process.env.AUDIT_LIMIT || 20000)); this.mirrors = []; }
	async load() { await mkdir(this.dir, { recursive: true }); if (!existsSync(this.file)) return this.db = freshDb(); try { this.db = migrate(JSON.parse(await readFile(this.file, 'utf8'))); } catch (error) { throw new Error(`Не удалось прочитать базу (отказ от перезаписи): ${error.message}`); } return this.db; }
	addMirror(mirror) { if (mirror) this.mirrors.push(mirror); }
	schedule(delay = 60) { this.dirty = true; clearTimeout(this.timer); this.timer = setTimeout(() => this.flush().catch((error) => console.error('DB write failed:', error)), delay); this.timer.unref?.(); }
	async flush() { clearTimeout(this.timer); this.timer = null; if (!this.dirty) return this.chain; this.dirty = false; const snapshot = JSON.stringify(this.db); this.chain = this.chain.then(async () => { await this.write(snapshot); for (const mirror of this.mirrors) await mirror.write(this.db); }); await this.chain; if (this.dirty) return this.flush(); return this.chain; }
	async write(data) { await mkdir(this.dir, { recursive: true }); const tmp = join(this.dir, `.db-${process.pid}-${randomBytes(6).toString('hex')}.tmp`); let handle; try { handle = await open(tmp, 'wx', 0o600); await handle.writeFile(data, 'utf8'); await syncQuietly(handle); await handle.close(); handle = null; await rename(tmp, this.file); try { const dir = await open(this.dir, 'r'); try { await syncQuietly(dir); } finally { await dir.close(); } } catch (error) { if (!IGNORABLE_SYNC.has(error.code)) throw error; } } catch (error) { if (handle) await handle.close().catch(() => {}); await unlink(tmp).catch(() => {}); throw error; } }
	audit(actor, action, entityType, entityId, metadata = {}) { this.db.audit.push({ id: id('aud'), actorId: actor?.id || null, actorNick: actor?.nick || 'system', action, entityType, entityId, metadata, at: now() }); if (this.db.audit.length > this.auditLimit) this.db.audit.splice(0, this.db.audit.length - this.auditLimit); this.schedule(); }
}
