import { CHUNK_SIZE } from '../http/chunks.mjs';
const keyFor = (x, y) => `${Math.floor(x / CHUNK_SIZE)}:${Math.floor(y / CHUNK_SIZE)}`;
export async function createPostgresMirror(connectionString) {
	if (!connectionString) return null;
	const { Pool } = await import('pg'); const pool = new Pool({ connectionString, max: Number(process.env.POSTGRES_POOL_SIZE || 4) }); await pool.query('SELECT 1');
	return {
		async write(db) { const client = await pool.connect(); try { await client.query('BEGIN'); for (const world of Object.values(db.worlds || {})) { const payload = { ...world, pixels: undefined, pixelHistory: undefined }; await client.query('INSERT INTO worlds (id, payload, updated_at) VALUES ($1, $2::jsonb, now()) ON CONFLICT (id) DO UPDATE SET payload = EXCLUDED.payload, updated_at = now()', [world.id, JSON.stringify(payload)]); const buckets = new Map(); for (const [cellKey, cell] of Object.entries(world.pixels || {})) { const i = cellKey.indexOf(':'); const x = Number(cellKey.slice(0, i)), y = Number(cellKey.slice(i + 1)), key = keyFor(x, y); let cells = buckets.get(key); if (!cells) buckets.set(key, (cells = {})); cells[cellKey] = cell; } await client.query('DELETE FROM world_chunks WHERE world_id = $1', [world.id]); for (const [key, cells] of buckets) { const [x, y] = key.split(':').map(Number); await client.query('INSERT INTO world_chunks (world_id, chunk_x, chunk_y, cells, revision) VALUES ($1, $2, $3, $4::jsonb, $5)', [world.id, x, y, JSON.stringify(cells), Date.now()]); } } await client.query('COMMIT'); } catch (error) { await client.query('ROLLBACK').catch(() => {}); throw error; } finally { client.release(); } },
		async readChunks(worldId, minX, maxX, minY, maxY) { const { rows } = await pool.query('SELECT chunk_x, chunk_y, cells FROM world_chunks WHERE world_id = $1 AND chunk_x BETWEEN $2 AND $3 AND chunk_y BETWEEN $4 AND $5', [worldId, minX, maxX, minY, maxY]); const out = new Map(); for (const row of rows) { const list = Object.entries(row.cells || {}).map(([key, cell]) => { const i = key.indexOf(':'); return [Number(key.slice(0, i)), Number(key.slice(i + 1)), cell.c]; }); out.set(`${row.chunk_x}:${row.chunk_y}`, list); } return out; },
		async close() { await pool.end(); }
	};
}
